### ISSUE TITLE
When I execute ./run.py, a TypeError occured.

### ISSUE THREAD

**Issue by hangtiancheng** [junchangwang/CUBIT#1]
When I execute ./run.py, a TypeError occured:
TypeError: a byte-like object is required, not 'str'.

generate.py:25
generate.py:26

```py
g.write("Created in ")        # g.write("Created in ".encode("utf-8"))
g.write(str(datetime.now()))  # g.write(str(datetime.now()).encode("utf-8"))
```
Updating these 2 lines (like comments) may help to solve this error.

**Comment by junchangwang** [comment]
Will be resolved in the upcoming commit. Thank you.
